"""initial dispute schema

Revision ID: 467f4d8206db
Revises: 
Create Date: 2026-07-23 15:10:17.087970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '467f4d8206db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('policy_id', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Text(), nullable=False),
    sa.Column('effective_to', sa.Text(), nullable=True),
    sa.Column('document_path', sa.String(length=255), nullable=False),
    sa.Column('document_json', sa.JSON(), nullable=False),
    sa.Column('loaded_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_versions_id_version')
    )
    op.create_index('ix_policy_versions_effective', 'policy_versions', ['policy_id', 'effective_from', 'effective_to'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('simulated_balance_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('BUYER','SELLER','REVIEWER','ADMIN')", name='ck_users_role'),
    sa.CheckConstraint('simulated_balance_minor >= 0', name='ck_users_balance_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('buyer_id', sa.String(length=80), nullable=False),
    sa.Column('seller_id', sa.String(length=80), nullable=False),
    sa.Column('listing_id', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('paid_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_at', sa.Text(), nullable=False),
    sa.Column('delivered_at', sa.Text(), nullable=True),
    sa.Column('order_status', sa.String(length=30), nullable=False),
    sa.Column('funds_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name='ck_transactions_currency_cny'),
    sa.CheckConstraint('paid_amount_minor >= 0', name='ck_transactions_amount_nonnegative'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_listing_id', 'transactions', ['listing_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('dispute_type', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('active_case_run_id', sa.String(length=80), nullable=True),
    sa.Column('question_round_count', sa.Integer(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('human_review_reasons_json', sa.JSON(), nullable=False),
    sa.Column('policy_id', sa.String(length=120), nullable=True),
    sa.Column('policy_version', sa.String(length=20), nullable=True),
    sa.Column('policy_basis_time', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('question_round_count BETWEEN 0 AND 3', name='ck_disputes_question_round'),
    sa.CheckConstraint('state_version >= 1', name='ck_disputes_state_version'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disputes_state', 'disputes', ['state'], unique=False)
    op.create_index('ix_disputes_transaction_id', 'disputes', ['transaction_id'], unique=False)
    op.create_table('listing_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('listing_id', sa.String(length=80), nullable=False),
    sa.Column('snapshot_type', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('immutable_uri', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.Text(), nullable=False),
    sa.CheckConstraint('length(content_sha256) = 64', name='ck_listing_snapshot_sha256'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'snapshot_type', name='uq_listing_snapshot_transaction_type')
    )
    op.create_table('shipment_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_transaction_time', 'shipment_events', ['transaction_id', 'occurred_at'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('transition_id', sa.String(length=10), nullable=True),
    sa.Column('from_state', sa.String(length=40), nullable=False),
    sa.Column('to_state', sa.String(length=40), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('expected_state_version', sa.Integer(), nullable=False),
    sa.Column('new_state_version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.CheckConstraint('new_state_version = expected_state_version + 1', name='ck_case_events_version_increment'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id', 'sequence', name='uq_case_events_dispute_sequence')
    )
    op.create_index('ix_case_events_dispute_time', 'case_events', ['dispute_id', 'occurred_at'], unique=False)
    op.create_table('case_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('checkpoint_json', sa.JSON(), nullable=False),
    sa.Column('tool_call_budget', sa.Integer(), nullable=False),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('phase_failure_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('paused_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('tokens_used >= 0 AND tokens_used <= token_budget', name='ck_case_runs_token_budget'),
    sa.CheckConstraint('tool_calls_used >= 0 AND tool_calls_used <= tool_call_budget', name='ck_case_runs_tool_budget'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id', 'run_number', name='uq_case_runs_dispute_number')
    )
    op.create_index('ix_case_runs_dispute_status', 'case_runs', ['dispute_id', 'status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('party', sa.String(length=10), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('responds_to_claim_id', sa.String(length=80), nullable=True),
    sa.Column('asserted_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("party IN ('BUYER','SELLER')", name='ck_claims_party'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responds_to_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_dispute_party', 'claims', ['dispute_id', 'party'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('submitted_by', sa.String(length=20), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('captured_at', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('immutable_uri', sa.String(length=255), nullable=False),
    sa.Column('integrity_status', sa.String(length=30), nullable=False),
    sa.Column('related_claim_ids_json', sa.JSON(), nullable=False),
    sa.Column('extracted_facts_json', sa.JSON(), nullable=False),
    sa.Column('handling_flags_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('length(content_sha256) = 64', name='ck_evidence_sha256'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id', 'content_sha256', name='uq_evidence_dispute_sha256')
    )
    op.create_index('ix_evidence_dispute_type', 'evidence', ['dispute_id', 'evidence_type'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=True),
    sa.Column('sender_id', sa.String(length=80), nullable=False),
    sa.Column('sender_role', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('snapshot_locked', sa.Boolean(), nullable=False),
    sa.CheckConstraint("sender_role IN ('BUYER','SELLER')", name='ck_messages_sender_role'),
    sa.CheckConstraint('length(content_sha256) = 64', name='ck_messages_sha256'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_transaction_sent', 'messages', ['transaction_id', 'sent_at'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('case_run_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_decision_id', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('length(content_sha256) = 64', name='ck_decisions_sha256'),
    sa.CheckConstraint('version >= 1', name='ck_decisions_version'),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id', 'version', name='uq_decisions_dispute_version')
    )
    op.create_table('open_questions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('case_run_id', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=10), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('missing_fact', sa.Text(), nullable=False),
    sa.Column('resolves_claim_ids_json', sa.JSON(), nullable=False),
    sa.Column('acceptable_evidence_types_json', sa.JSON(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('deadline', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.CheckConstraint("target IN ('BUYER','SELLER')", name='ck_open_questions_target'),
    sa.CheckConstraint('round_number BETWEEN 1 AND 3', name='ck_open_questions_round'),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_open_questions_dispute_status', 'open_questions', ['dispute_id', 'status'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=True),
    sa.Column('case_run_id', sa.String(length=80), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('result_summary_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('called_at', sa.Text(), nullable=False),
    sa.CheckConstraint('duration_ms >= 0', name='ck_tool_calls_duration'),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_case_run', 'tool_calls', ['case_run_id', 'called_at'], unique=False)
    op.create_index('ix_tool_calls_name', 'tool_calls', ['tool_name'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('appellant_role', sa.String(length=10), nullable=False),
    sa.Column('grounds', sa.String(length=30), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appeals_dispute_status', 'appeals', ['dispute_id', 'status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('reviewer_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decision_content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("action IN ('APPROVE','REJECT')", name='ck_approvals_action'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'action', name='uq_approvals_decision_action')
    )
    op.create_table('resolution_actions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name='ck_resolution_actions_currency'),
    sa.CheckConstraint('amount_minor IS NULL OR amount_minor >= 0', name='ck_resolution_actions_amount'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_resolution_actions_dispute_status', 'resolution_actions', ['dispute_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resolution_actions_dispute_status', table_name='resolution_actions')
    op.drop_table('resolution_actions')
    op.drop_table('approvals')
    op.drop_index('ix_appeals_dispute_status', table_name='appeals')
    op.drop_table('appeals')
    op.drop_index('ix_tool_calls_name', table_name='tool_calls')
    op.drop_index('ix_tool_calls_case_run', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_open_questions_dispute_status', table_name='open_questions')
    op.drop_table('open_questions')
    op.drop_table('decisions')
    op.drop_index('ix_messages_transaction_sent', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_evidence_dispute_type', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_claims_dispute_party', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_case_runs_dispute_status', table_name='case_runs')
    op.drop_table('case_runs')
    op.drop_index('ix_case_events_dispute_time', table_name='case_events')
    op.drop_table('case_events')
    op.drop_index('ix_shipment_transaction_time', table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_table('listing_snapshots')
    op.drop_index('ix_disputes_transaction_id', table_name='disputes')
    op.drop_index('ix_disputes_state', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_transactions_listing_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_index('ix_policy_versions_effective', table_name='policy_versions')
    op.drop_table('policy_versions')
    # ### end Alembic commands ###
