"""add agent outputs and question provenance

Revision ID: dfc87f87bc84
Revises: 467f4d8206db
Create Date: 2026-07-23 17:24:49.314902
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dfc87f87bc84'
down_revision: Union[str, Sequence[str], None] = '467f4d8206db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_outputs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('case_run_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('output_type', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('usage_json', sa.JSON(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('length(content_sha256) = 64', name='ck_agent_outputs_content_hash'),
    sa.CheckConstraint('length(input_fingerprint) = 64', name='ck_agent_outputs_input_hash'),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_run_id', 'role', 'output_type', 'input_fingerprint', name='uq_agent_outputs_run_role_input')
    )
    op.create_index('ix_agent_outputs_case_role', 'agent_outputs', ['dispute_id', 'role', 'created_at'], unique=False)
    op.create_index('ix_agent_outputs_run_type', 'agent_outputs', ['case_run_id', 'output_type'], unique=False)
    with op.batch_alter_table('decisions') as batch_op:
        batch_op.add_column(sa.Column('agent_output_id', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint('uq_decisions_agent_output_id', ['agent_output_id'])
        batch_op.create_foreign_key(
            'fk_decisions_agent_output_id_agent_outputs',
            'agent_outputs',
            ['agent_output_id'],
            ['id'],
            ondelete='SET NULL',
        )
    op.add_column('open_questions', sa.Column('dedupe_key', sa.String(length=64), nullable=True))
    op.add_column(
        'open_questions',
        sa.Column('basis_evidence_ids_json', sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.add_column('open_questions', sa.Column('generation_reason', sa.String(length=80), nullable=True))
    op.create_index('ix_open_questions_dedupe', 'open_questions', ['dispute_id', 'dedupe_key', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_open_questions_dedupe', table_name='open_questions')
    op.drop_column('open_questions', 'generation_reason')
    op.drop_column('open_questions', 'basis_evidence_ids_json')
    op.drop_column('open_questions', 'dedupe_key')
    with op.batch_alter_table('decisions') as batch_op:
        batch_op.drop_constraint('fk_decisions_agent_output_id_agent_outputs', type_='foreignkey')
        batch_op.drop_constraint('uq_decisions_agent_output_id', type_='unique')
        batch_op.drop_column('agent_output_id')
    op.drop_index('ix_agent_outputs_run_type', table_name='agent_outputs')
    op.drop_index('ix_agent_outputs_case_role', table_name='agent_outputs')
    op.drop_table('agent_outputs')
    # ### end Alembic commands ###
