"""add decision guard reports

Revision ID: fcbcee15aca3
Revises: dfc87f87bc84
Create Date: 2026-07-23 17:50:25.138242
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fcbcee15aca3'
down_revision: Union[str, Sequence[str], None] = 'dfc87f87bc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_guard_reports',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('dispute_id', sa.String(length=80), nullable=False),
    sa.Column('case_run_id', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=80), nullable=False),
    sa.Column('guard_version', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('required_action', sa.String(length=40), nullable=False),
    sa.Column('violations_json', sa.JSON(), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('decision_content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('length(content_sha256) = 64', name='ck_guard_reports_content_hash'),
    sa.CheckConstraint('length(decision_content_sha256) = 64', name='ck_guard_reports_decision_hash'),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', name='uq_guard_reports_decision')
    )
    op.create_index('ix_guard_reports_case_run', 'decision_guard_reports', ['dispute_id', 'case_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guard_reports_case_run', table_name='decision_guard_reports')
    op.drop_table('decision_guard_reports')
    # ### end Alembic commands ###
